select * from customer limit 20

SELECT column_name
FROM information_schema.columns
WHERE table_name = 'customer';

--1. What is the total revenue generated by male vs. female customers?
SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";

--2. which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes' 
  AND "Purchase Amount (USD)" > (SELECT AVG("Purchase Amount (USD)") FROM customer);

  
--3. which are the top 5 products with the highest average review rating?
SELECT "Product", AVG("Review Rating") AS avg_rating
FROM customer
GROUP BY "Product"
ORDER BY avg_rating DESC
LIMIT 5;


--4. compare the average purchase amounts between standard and express shipping.
SELECT "Shipping Type", AVG("Purchase Amount (USD)") AS avg_spend
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";


--5. Do subscribed customers spend more ? compare average spend and total revenue between subscribers and non subscribers.
SELECT "Subscription Status", AVG("Purchase Amount (USD)") AS avg_spend, SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Subscription Status";


--6. which 5 products have the highest percentage of purchases with discount applied?
SELECT 
    "Product",
    COUNT(CASE WHEN "Discount Applied" = 'Yes' THEN 1 END) AS discounted_purchases,
    COUNT(*) AS total_purchases,
    ROUND(
        (COUNT(CASE WHEN "Discount Applied" = 'Yes' THEN 1 END)::NUMERIC / COUNT(*)::NUMERIC) * 100, 
        2
    ) AS discount_percentage
FROM customer
GROUP BY "Product"
ORDER BY discount_percentage DESC
LIMIT 5;

--7. segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT 
    CASE 
        WHEN "Previous Purchases" <= 3 THEN 'New Customer'
        WHEN "Previous Purchases" BETWEEN 4 AND 10 THEN 'Returning Customer'
        ELSE 'Loyal Customer'
    END AS customer_segment,
    COUNT(*) AS total_customers
FROM customer
GROUP BY customer_segment
ORDER BY total_customers DESC;


--8. what are the top 3 most purchased product within each category
WITH ranked_products AS (
    SELECT 
        "Category",
        "Product",
        COUNT(*) AS purchase_count,
        DENSE_RANK() OVER (
            PARTITION BY "Category" 
            ORDER BY COUNT(*) DESC
        ) AS rank
    FROM customer
    GROUP BY "Category", "Product"
)
SELECT 
    "Category",
    "Product",
    purchase_count
FROM ranked_products
WHERE rank <= 3
ORDER BY "Category", rank;
--9. Are customers who are repeat buyers (more than 5 previous purchase)also likely to subscribe?
SELECT  CASE WHEN "Previous Purchases" > 5 THEN 'Repeat Buyer (>5 Purchases)'       
ELSE 'Regular Buyer (<=5 Purchases)'   
END AS buyer_type,  COUNT(*) AS total_customers,    
COUNT(CASE WHEN "Subscription Status" = 'Yes' THEN 1 END) AS subscribers,    
ROUND((COUNT(CASE WHEN "Subscription Status" = 'Yes' THEN 1 END)::NUMERIC / COUNT(*)::NUMERIC) * 100,2
    ) AS subscription_rate
FROM customer
GROUP BY buyer_type;

--10. What is the revenue contribution of each age group?
WITH age_segments AS (
    SELECT 
        CASE 
            WHEN "Age" BETWEEN 18 AND 25 THEN '18-25'
            WHEN "Age" BETWEEN 26 AND 35 THEN '26-35'
            WHEN "Age" BETWEEN 36 AND 50 THEN '36-50'
            WHEN "Age" >= 51 THEN '51+'
            ELSE 'Unknown'
        END AS age_group,
        "Purchase Amount (USD)" AS revenue
    FROM customer
)
SELECT 
    age_group,
    SUM(revenue) AS total_revenue,
    ROUND(
        (SUM(revenue) / (SELECT SUM("Purchase Amount (USD)") FROM customer)) * 100, 
        2
    ) AS revenue_percentage
FROM age_segments
GROUP BY age_group
ORDER BY total_revenue DESC;